spring:
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: provider-application
          uri: lb://provider-application
          predicates:
            - Path=/user/**
        - id: consumer-application
          uri: lb://consumer-application
          predicates:
            - Path=/**
      discovery:
        locator:
          enabled: true