logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: debug
  config: classpath:logback-spring.xml
spring:
  zipkin:
    base-url: http://localhost:9411
user:
  name: test-provider
